In [56]:
text="""A nation can progress and attain higher development growth only when both men and women are entitled to equal opportunities. Women in the society are often cornered and are refrained from getting equal rights as men to health, education, decision-making and economic independence in terms of wages.

The social structure that prevails since long in such a way that girls do not get equal opportunities as men. Women generally are the caregivers in the family. Because of this, women are mostly involved in household activities. There is lesser participation of women in higher education, decision-making roles, and leadership roles. This gender disparity is a hindrance in the growth rate of a country. When women participate in the workforce increases the economic growth rate of the country increases. Gender equality increases the overall wellbeing of the nation along with
Gender equality is an important factor in determining a country’s overall growth. There are several indexes to measure gender equality.

Gender-Related Development Index (GDI)    GDI is a gender centric measure of Human Development Index. GDI considers parameters like life expectancy, education, and incomes in assessing the gender equality of a country.

Gender Empowerment Measure (GEM)  This measure includes much detail aspects like the proportion of seats than women candidates hold in national parliament, percentage of women at economic decision-making role, the income share of female employees.

Gender Equity Index (GEI)  GEI ranks countries on three parameters of gender inequality, those are education, economic participation, and empowerment. However, GEI ignores the health parameter.

Global Gender Gap Index  The World Economic Forum introduced the Global Gender Gap Index in 2006. This index focuses more on identifying the level of female disadvantage. The four important areas that the index considers are economic participation and opportunity, educational attainment, political empowerment, health, and survival rate.
As per the World Economic Forum’s gender gap ranking, India stands at rank 108 out of 149 countries. This rank is a major concern as it highlights the immense gap in opportunities in women with comparison to men. In Indian society from a long time back, the social structure has been such that the women are neglected in many areas like education, health, decision-making areas, financial independence, etc.

You can check the information on- https://www.youtube.com/watch?v=_04qU5kbxjg

We are so grateful to have here- https://www.youtube.com/watch?v=qMJQ6JVkjeM

Another major reason, which contributes to the discriminatory behavior towards women in India, is the dowry system in marriage.  Because of this dowry system, most Indian families consider girls as a burden.  Preference for son still prevails. Girls have refrained from higher education. Women are not entitled to equal job opportunities and wages. In the 21st century, women are still preferred gender in home managing activities. Many women quit their job and opt-out from leadership roles because of family commitments. However, such actions are very uncommon among men.
For overall wellbeing and growth of a nation, scoring high on gender equality is the most crucial aspect. Countries with less disparity in gender equality have progressed a lot. The government of India has also started taking steps to ensure gender equality. Several laws and policies are prepared to encourage girls. “Beti Bachao, Beti Padhao Yojana” (Save girl, and make girls educated) campaign is created to spread awareness of the importance of girl child.  Several laws to protect girls are also there. However, we need more awareness of spreading knowledge of women rights. In addition, the government should take initiatives to check the correct and proper implementation of policies."""

In [51]:
#to remove superscript texts
import unicodedata
text = "".join(c for c in text if unicodedata.category(c) not in ["No", "Lo"])

In [58]:
#to remove puctuation errors
import string
for punctuation in string.punctuation:
    text = text.replace(punctuation, '')

In [59]:
#to convert all the values to lower case
text=text.lower()

In [57]:
#to remove all the URLs
import re
hello = re.sub(r'http\S+', '', text, flags=re.MULTILINE)

In [60]:
print(text)

a nation can progress and attain higher development growth only when both men and women are entitled to equal opportunities women in the society are often cornered and are refrained from getting equal rights as men to health education decisionmaking and economic independence in terms of wages

the social structure that prevails since long in such a way that girls do not get equal opportunities as men women generally are the caregivers in the family because of this women are mostly involved in household activities there is lesser participation of women in higher education decisionmaking roles and leadership roles this gender disparity is a hindrance in the growth rate of a country when women participate in the workforce increases the economic growth rate of the country increases gender equality increases the overall wellbeing of the nation along with
gender equality is an important factor in determining a country’s overall growth there are several indexes to measure gender equality

gen

In [34]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [35]:
mytokenizer = Tokenizer()
mytokenizer.fit_on_texts([text])
total_words = len(mytokenizer.word_index) + 1

In [36]:
len(mytokenizer.word_index)

255

In [37]:
input_sequences = []
for sentence in text.split('\n'):
  tokenized_sentence = mytokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

In [38]:
max_sequence_len = max([len(seq) for seq in input_sequences])
input_sequences = np.array(pad_sequences(input_sequences, maxlen=max_sequence_len, padding='pre'))

In [39]:
input_sequences[1]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  8, 29, 52])

In [40]:
X = input_sequences[:, :-1]
y = input_sequences[:, -1]

In [41]:
X[1]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  8, 29])

In [42]:
y

array([ 29,  52,  97,   5,  98,  30,  31,  17,  99,  53, 100,  18,   5,
         6,   7,  54,   9,  20,  21,   6,   3,   1,  55,   7, 101, 102,
         5,   7,  56,  22, 103,  20,  57,  19,  18,   9,  23,  14,  24,
         5,  11,  58,   3, 104,   2,  59,  60,  61,  25,  62, 105,  63,
         3,  32,   8, 106,  25,  15, 107,  64, 108,  20,  21,  19,  18,
         6, 109,   7,   1, 110,   3,   1,  65,  33,   2,  16,   6,   7,
       111, 112,   3, 113,  66,  34,  10, 114,  35,   2,   6,   3,  30,
        14,  24,  36,   5,  67,  36,  16,   4,  68,  10,   8, 115,   3,
         1,  17,  37,   2,   8,  38,  53,   6, 116,   3,   1, 117,  39,
         1,  11,  17,  37,   2,   1,  38,  39,   4,  12,  39,   1,  40,
        69,   2,   1,  29, 118,  41,  12,  10, 119,  70, 120,   3, 121,
         8, 122,  40,  17,  34,   7,  42, 123,   9,  26,   4,  12,  31,
        13,  43,  43,  10,   8,   4, 125,  26,   2, 126,  31,  13,  43,
        71,  72,  44, 127, 128,  14,   5, 129,   3, 130,   1,   

In [43]:
y = np.array(tf.keras.utils.to_categorical(y, num_classes=total_words))

In [44]:
y[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [45]:
model = Sequential()
model.add(Embedding(total_words, 100, input_length=max_sequence_len-1))
model.add(LSTM(150))
model.add(Dense(total_words, activation='softmax'))

In [46]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 108, 100)          25600     
                                                                 
 lstm_1 (LSTM)               (None, 150)               150600    
                                                                 
 dense_1 (Dense)             (None, 256)               38656     
                                                                 
Total params: 214,856
Trainable params: 214,856
Non-trainable params: 0
_________________________________________________________________


In [47]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=100, verbose=1)

Epoch 1/100
18/18 [==============================] - 10s 126ms/step - loss: 5.5229 - accuracy: 0.0353
Epoch 2/100
18/18 [==============================] - 2s 129ms/step - loss: 5.2499 - accuracy: 0.0477
Epoch 3/100
18/18 [==============================] - 2s 124ms/step - loss: 5.0815 - accuracy: 0.0548
Epoch 4/100
18/18 [==============================] - 2s 124ms/step - loss: 5.0469 - accuracy: 0.0548
Epoch 5/100
18/18 [==============================] - 2s 125ms/step - loss: 5.0356 - accuracy: 0.0548
Epoch 6/100
18/18 [==============================] - 2s 126ms/step - loss: 5.0146 - accuracy: 0.0548
Epoch 7/100
18/18 [==============================] - 2s 125ms/step - loss: 4.9690 - accuracy: 0.0671
Epoch 8/100
18/18 [==============================] - 2s 126ms/step - loss: 4.9133 - accuracy: 0.0830
Epoch 9/100
18/18 [==============================] - 2s 123ms/step - loss: 4.8439 - accuracy: 0.0742
Epoch 10/100
18/18 [==============================] - 2s 119ms/step - loss: 4.7460 - accur

In [48]:
input_text = "another major reason"
predict_next_words= 6

for _ in range(predict_next_words):
    token_list = mytokenizer.texts_to_sequences([input_text])[0]
    print(token_list)
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    output_word = ""
    for word, index in mytokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    input_text += " " + output_word

print(input_text)

[193, 79, 194]


1/1 [==============================] - 1s 787ms/step
[193, 79, 194, 195]
1/1 [==============================] - 0s 53ms/step
[193, 79, 194, 195, 196]
1/1 [==============================] - 0s 52ms/step
[193, 79, 194, 195, 196, 9]
1/1 [==============================] - 0s 56ms/step
[193, 79, 194, 195, 196, 9, 1]
1/1 [==============================] - 0s 53ms/step
[193, 79, 194, 195, 196, 9, 1, 197]
1/1 [==============================] - 0s 49ms/step
another major reason which contributes to the discriminatory behavior


In [49]:
score = model.evaluate(X,y, verbose = 0) 

print('Test loss:', score[0]) 
print('Test accuracy:', score[1])

Test loss: 0.054992325603961945
Test accuracy: 0.9964664578437805
